baseURL                = "https://1689006.xyz/"
locale                 = "zh"
title                  = "我的博客"
# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "zh"
# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage         = true

theme = "hugo-theme-stack"

[pagination]
    pagerSize = 3

[permalinks]
    posts = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"

[services]
  [services.googleAnalytics]
    id = 'G-68G2LEB5G5'

    